experience_bonus_mult bug fix
Error: Json(Error("invalid type: floating point `1.15`, expected u64", line: 1, column: 191630))
Causes a JSON error because it can be a floating point but is declared as an integer
This is backed up because of the value of ExperienceBonusMult in my profile's JSON is 1.15.